kind: ImageStream
apiVersion: image.openshift.io/v1

metadata:
  name: dtwin-mcp-server
  labels:
    app: dtwin-mcp-server
spec:
  lookupPolicy:
    local: false
  tags:
    - name: staging
      from:
        kind: DockerImage
        name: jensjvh/dtwin:mcp-server
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
